### ISSUE TITLE
5/31 Review Code

### ISSUE THREAD

**Issue by hsiangfeng** [larrylinr5/posts_final#86]
## 主要審核分支 main

cc. @Charlie50503

- README 可以盡可能撰寫一下，多介紹自己的後端環境與作品，可包含使用了哪些技術、如何運行與使用 `cp` 複製 `env`。
- `env` 的 `DATABASE_PASSWORD` 少一個等號。
- 可以試著加入 ESLint。
- README 可以增加一下 env 描述，或者在 env 稍微註解說明一下用途，舉例來講 `GOOGLE_ID` 就非常不明確是什麼 `ID`，正確建議是 `GOOGLE_CLIENT_ID` 會比較好，更能一讀就懂哦。
- 正常來講是採用前後端分離狀況下是不需要額外設置 Session 的。
- 檔案的縮排都不統一，請盡可能統一縮排。
- 可以試著增加 Swagger 文件或者是 Postman 供前端直接測試。
- routes 的檔案可以試著將寫法改變一下，不用特別在額外 callback 一次哦

```jsx
// 原始
/* 搜尋所有貼文 */
router.get('/', isAuth, handleErrorAsync(async(req, res, next) => {
  PostController.getAllPosts(req, res, next);
}));

// 調整
/* 搜尋所有貼文 */
router.get('/', isAuth, handleErrorAsync(PostController.getAllPosts));
```

- 沒有用處的 API 建議刪除，如 general.js 的預設首頁、users.js 12 行。
- 可以試著使用傳統函式縮寫。

```jsx
// 調整前
getAllPosts: handleErrorAsync(async (req, res, next) => { ... })
```

- `handleErrorAsync` 已經在 routes 已經有包了，因此 controller 就不用再包 `handleErrorAsync`，只需要傳統函式縮寫就好。
- 單雙引號請統一，如：controllers/postController.js 19 行
- 沒有使用的參數請刪除，如：controllers/postController.js 11 行的 `next`。
- controllers/postController.js 12 行，可以稍微換行一下。

```jsx
// 原始
const { query, params: { userId } } = req

// 調整
const {
      query,
      params: {
        userId
      }
    } = req;
```

- controllers/postController.js 78 行可以改成 `data`，這樣就可以與下方相同直接物件縮寫形式解決。
- `totalDatas` ⇒ `totalData`。
- `const` 跟 `let` 可以區分一下。
- 撰寫 `if` 的時候盡量不要省略 `{}` 花括號（不是在寫 Python。）
- 沒有正確駝峰大小寫，如：controllers/userController.js 的 84 行 oldpassword ⇒ oldPassword。
- 許多地方字串都是可以省略的，如下

```jsx
// controllers/userController.js 99 行
res.status(201).json(getHttpResponse({ "message": "更新密碼成功" }));

// 調整後
res.status(201).json(getHttpResponse({
  message:"更新密碼成功"
}));
```

- 可以使用換行區分相關程式碼，盡量不要全部都擠在一起。
- followModel.js 的第 7 行叫 `editor` 有一點神奇，神奇到自己都要寫註解說自己了，可以考慮直接命名為  `follow`。
- 不用額外再宣告一個變數放資料，直接寫進去 res 就好了，如：controllers/fileController.js 23 行，如果是擔心巢狀過巢的話，反而建議直接改成以下就好

```jsx
// 原始
const resData = {
    upload: data.link
}

if (success) {
    res.status(201).json(getHttpResponse({ data: resData }));
} else {
    return next(appError(status, "", "發生錯誤，請稍後再試"))
}

// 調整
// 寫法 1

res.status(201).json(getHttpResponse({
    data: {
        upload: data.link
    }
}));

// 寫法 2
res.status(201).json(getHttpResponse({ url: data.link }));
```

## 須注意地方

- 由於沒有上 ESLint 變成各自風格各自寫各自的，建議要多加注意這一點問題。
- 許多地方的會習慣忽略花括號，但可以的話請盡量避免這種寫法，畢竟我們不是寫 Python。

**Comment by justin3737** [comment]
以上問題均已修正，謝謝 Ray
